[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/next"